# This is the Gitlab CI pipeline for the pre-generated garden-rs.gitlab.io repository
# and is installed to doc/book/.gitlab-ci.yml
pages:
  image: alpine
  script:
    - apk add --update rsync
    - rsync -ar --exclude=public ./ ./public/
    - echo "Read the pre-generated documentation at $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  publish: public
  only:
    - pages
