stages:
  - pages

pages:
  image: alpine
  script:
    - apk --nocache add rsync
    - rsync -ar --exclude=public ./ ./public/
    - echo "Read the pre-generated documentation at $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  publish: public
  only:
    - main
