[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    # egui
    "BSL-1.0",
    # egui
    "BSD-2-Clause",
    # encoding_rs
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
    # egui and others
    "Zlib",
]

exceptions = [
    # egui
    { allow = ["OFL-1.1", "Ubuntu-font-1.0"], crate = "epaint_default_fonts" },
    { allow = ["ISC"], crate = "libloading" },
    # dirs
    { allow = ["MPL-2.0"], crate = "option-ext" },
]

[bans]
skip = [
    "bitflags",
    "core-foundation",
    "getrandom",
    "quick-xml",
    "redox_syscall",
    "thiserror-impl",
    "wasi",
]

skip-tree = [
    "dirs",
    "strum",
    "thiserror",
    "windows-sys",
]
